yarnPath: .yarn/releases/yarn-sources.js
packageExtensions:
    'gatsby-recipes@*':
        dependencies:
            'eslint': '*'
            'webpack': '*'
            'gatsby': '*'
            'ink': '*'
            'react': '*'
            'react-dom': '*'
    'gatsby@*':
        dependencies:
            '@types/react': '*'
    'gatsby-plugin-typescript@*':
        dependencies:
            'graphql': '^14.1.1'
    '@stylelint/postcss-markdown@*':
        dependencies:
            'postcss-html': '*'
